model:
  input_shape: [128, 728, 1]  # Update this to match your actual input shape
  latent_dim: 128

training:
  learning_rate: 0.005
  epochs: 50
  batch_size: 128
  model_save_path: 'checkpoints/'
  final_model_save_path: 'models/trained/final_autoencoder.h5'  # Path to save the final model
  tensorboard_log_dir: 'logs/tensorboard'  # Directory for TensorBoard logs
